# Generated by Django 4.1 on 2023-02-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_picture_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='img',
            field=models.ImageField(height_field='400', upload_to='', width_field='400'),
        ),
    ]
