# Generated by Django 4.1 on 2023-02-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_picture_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='img',
            field=models.ImageField(upload_to='', width_field='img_width'),
        ),
    ]
