# Generated by Django 4.1 on 2023-02-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('phone', models.BigIntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('prof_pic', models.ImageField(upload_to='')),
                ('sign_up_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
