# Generated by Django 4.1 on 2023-02-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prof_pic',
            field=models.ImageField(null=True, upload_to='profpics/'),
        ),
        migrations.AddField(
            model_name='user',
            name='special_til',
            field=models.DateTimeField(null=True),
        ),
    ]
