# Generated by Django 4.1 on 2023-02-14 00:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_prof_pic_user_special_til'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='special_til',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
