# Generated by Django 4.1 on 2023-02-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_prof_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='prof_pic',
            field=models.ImageField(blank=True, default='profpics/defult.jpg', null=True, upload_to='profpics/'),
        ),
    ]
